#!/bin/bash

# Path to the ELF file generated by the build process
ELF_FILE="firmware/iot-risk-logger-stm32l4/build/iot-risk-logger-stm32l4.elf"

# Run arm-none-eabi-size and capture the output
SIZE_OUTPUT=$(arm-none-eabi-size $ELF_FILE)

# Extract text, data, and bss values
TEXT_SIZE=$(echo "$SIZE_OUTPUT" | awk 'NR==2 {print $1}')
DATA_SIZE=$(echo "$SIZE_OUTPUT" | awk 'NR==2 {print $2}')
BSS_SIZE=$(echo "$SIZE_OUTPUT" | awk 'NR==2 {print $3}')

# Calculate Flash usage (text + data)
FLASH_USAGE=$((TEXT_SIZE + DATA_SIZE))

# Calculate RAM usage (data + bss)
RAM_USAGE=$((DATA_SIZE + BSS_SIZE))

# Print the results
echo "Memory usage:"
echo "Flash usage: $FLASH_USAGE bytes"
echo "RAM usage: $RAM_USAGE bytes"

# Update README.md with the new values
#sed -i "/## Flash and RAM Usage/c\## Flash and RAM Usage\n\n- Flash: $FLASH_USAGE bytes\n- RAM: $RAM_USAGE bytes" README.md

