M48
; DRILL file {KiCad 8.0.0} date 2024-03-21T16:00:11+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-21T16:00:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X2.9832Y-1.5822
X2.9832Y-1.8097
T2
X2.73Y-1.2801
X2.77Y-1.5801
X2.81Y-1.2801
M30
