M48
; DRILL file {KiCad 9.0.4} date 2025-11-06T01:48:05+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-06T01:48:05+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X79.395Y-40.61
X79.395Y-46.39
T2
X75.438Y-32.893
X75.438Y-34.925
X83.058Y-33.909
M30
